apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: COSA-Pod-ephemeral
  template: COSA-Pod-ephemeral-template
metadata:
  annotations:
    openshift.io/display-name: COSA Pod (Ephemeral)
  name: COSA-Pod-ephemeral
objects:


# Create the Service Account for COSA
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      coreos-assembler.coreos.com/type: "service account"
    name: ${SA}
  name: ${SA}

- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: coreos-builder-editor-0
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
  subjects:
  - kind: ServiceAccount
    name: ${SA}

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${COSA_POD_NAME}
  spec:
    replicas: 1
    selector:
      name: ${COSA_POD_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${COSA_POD_NAME}
      spec:
        containers:
        - env:
            - name: OC_BIN_URL
              value: "https://mirror.openshift.com/pub/openshift-v4/clients/oc/4.5/linux/oc.tar.gz"
          args:
            - /bin/bash
            - -c
            - 'chmod 0666 /dev/kvm; (cd /tmp; curl $OC_BIN_URL -O; tar -C /srv -xvvf oc.tar.gz); exec sleep infinity'
          command:
            - /usr/bin/dumb-init
          image: coreos-assembler:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          name: ${COSA_POD_NAME}
          securityContext:
            runAsUser: 0
            runAsGroup: 1000
            privileged: true
          tty: true
          resources:
            limits:
              memory: "1Gi"
              cpu: "2000m"
            requests:
              memory: "1Gi"
              cpu: "2000m"
          volumeMounts:
          - mountPath: /srv
            name: srv
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - name: srv
          emptyDir:
            medium: ""
        serviceAccount: jenkins-kvm
        serviceAccountName: jenkins-kvm
        securityContext:
          runAsUser: 0
          runAsGroup: 1000
          privileged: true
    triggers:
        - type: "ImageChange"
          imageChangeParams:
            automatic: true
            from:
              kind: "ImageStreamTag"
              name: "coreos-assembler:${IMAGE_TAG}"
            containerNames:
              - "${COSA_POD_NAME}"

parameters:
- description: The COSA Pod Name
  displayName: COSA Pod Service Name
  name: COSA_POD_NAME
  value: cosa-podder

- description: Tag of the COSA image
  displayName: COSA Image Tag to use
  name: IMAGE_TAG
  value: buildconfig-master

- description: Service Account
  name: SA
  value: cosa-podder

