apiVersion: v1
kind: Template
labels:
  app: cosa-dev
  template: cosa-dev
metadata:
  annotations:
    description: CoreOS Assembler Dev Images
    openshift.io/display-name: CoreOS Assembler DEV
    tags: cosa-dev
  name: cosa-dev


objects:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      labels:
        app: cosa-podder
      name: cosa-podder
    spec:
      # kill the build after 3hrs
      completionDeadlineSeconds: 13200
      lookupPolicy:
        local: true
      output:
        to:
          kind: ImageStreamTag
          name: coreos-assembler:podder
      postCommit: {}
      runPolicy: Serial
      source:
        git:
          uri: "https://github.com/darkmuggle/centos-ocp"
          ref: "patronus"
        type: Git
      strategy:
        dockerStrategy:
          dockerfilePath: Dockerfile.cosa-podder
          from:
            kind: ImageStreamTag
            name: coreos-assembler:master
        type: Docker
        dockerfilePath: Dockerfile.cosa-podder
      triggers:
        - type: ConfigChange
        - type: "ImageChange"
          imageChange:
              from:
                kind: "ImageStreamTag"
                name: coreos-assembler:master
