apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: COSA-Pod-ephemeral
  template: COSA-Pod-ephemeral-template
metadata:
  annotations:
    openshift.io/display-name: COSA Pod (Ephemeral)
  name: COSA-Pod-ephemeral
objects:

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${COSA_POD_NAME}
  spec:
    replicas: 1
    selector:
      name: ${COSA_POD_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${COSA_POD_NAME}
      spec:
        containers:
        - capabilities: {}
          image: 'coreos-assembler:podder'
          imagePullPolicy: IfNotPresent
          name: ${COSA_POD_NAME}
          resources:
            limits:
              memory: "4Gi"
              cpu: "2000m"
              devices.kubevirt.io/kvm: "1"
            requests:
              memory: "4Gi"
              cpu: "2000m"
              devices.kubevirt.io/kvm: "1"
          volumeMounts:
          - mountPath: /srv
            name: srv
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - name: srv
          emptyDir:
            medium: ""

parameters:
- description: The COSA Pod Name
  displayName: COSA Pod Service Name
  name: COSA_POD_NAME
  value: cosa-podder
