apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coreos-builder-editor-0
  namespace: ben-fcos-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: coreos-builder

